apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: mealplan
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: mealplan
      tier: frontend
  template:
    metadata:
      labels:
        app: mealplan
        tier: frontend
    spec:
      containers:
        - image: "coderjourney/mealplan-frontend:1.0.0"
          name: nginx
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]

